### ISSUE TITLE
Error on build with plugin ibm-mfp-push

### ISSUE THREAD

**Issue by belamrani** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#14]
Hello,

The last commit you've made seems to break the plugin ibm-mfp-push. Indeed, when i try to build android platform i have the following error : 

CDVMFPPush.java:36: error: cannot find symbol
    private static final Logger pushLogger = Logger.getInstance(Logger.INTERNAL_PREFIX + "CDVMFPPush");
                                                   ^
  symbol:   method getInstance(String)
  location: class Logger

I saw that you've made some change in the file CDVMFPLogger.java. Maybe the problem is here ?? 

Any idea ?

**Comment by rotembr** [comment]
Hello, 
I reverted the changes in the Master branch, the 'ibm-mfp-push' plugin should build successfully now.
