### ISSUE TITLE
Got error - com.google.android.gms.auth.UserRecoverableAuthException: NeedPermission

### ISSUE THREAD

**Issue by andaralex** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#21]
08-26 00:16:10.340 28081-28081/com.ionicframework.inspectorapp430070 W/CordovaInterfaceImpl: Got an activity result, but no plugin was registered to receive it.
08-26 00:16:11.569 28081-31117/com.ionicframework.inspectorapp430070 W/GoogleAuthUtil: isUserRecoverableError status: NEED_PERMISSION
08-26 00:16:11.574 28081-29684/com.ionicframework.inspectorapp430070 E/DefaultGoogleAuthenticationListener: DefaultGoogleAuthenticationListener$RetrieveTokenTask.doInBackground in DefaultGoogleAuthenticationListener.java:170 :: Error getting google token: NeedPermission
08-26 00:16:11.577 28081-29684/com.ionicframework.inspectorapp430070 E/mfpsdk.AuthorizationRequestAgent: AuthorizationRequestAgent.requestFailed in AuthorizationRequestAgent.java:490 :: BaseRequest failed with info: {"errorCode":"101","msg":"GoogleAuth - Token returned null, canont login"}
08-26 00:16:11.580 28081-29684/com.ionicframework.inspectorapp430070 E/mfpsdk.AuthorizationProcessManager: AuthorizationProcessManager.handleAuthorizationFailure in AuthorizationProcessManager.java:443 :: authorization process failed
08-26 00:16:11.582 28081-29684/com.ionicframework.inspectorapp430070 E/mfpsdk.CDVMFPRequest: CDVMFPRequest$1$1.onFailure in CDVMFPRequest.java:80 :: Failed to send request.

**Comment by andaralex** [comment]
![screenshot_10](https://cloud.githubusercontent.com/assets/922142/17982009/b33e80bc-6b23-11e6-9ee8-5d93a6a3e151.png)

**Comment by vitalymibm** [comment]
Please make sure that you correctly initialize BMSClient with clientId or tenantId obtained from MCA credentials. Do not use appGuid copied from the Mobile Options App GUID field. This is applied to newly created MCA service instances. Also note, that an old MCA service instance (instance created before Aug 24) can't be unbound and then bound again to any application. The instance should be recreated and reconfigured again. Please let us know how it helps.

**Comment by andaralex** [comment]
I have created MCA service instance newly by today morning only. Also I have configured the BMSClient and its credentials correctly as per the given document.

**Comment by andaralex** [comment]
Even the given code is not supported com.ibm.mobilefirstplatform.clientsdk.android : 2+

**Comment by vitalymibm** [comment]
Can you try to clear the gradle cache and ensure that you're getting the latest versions of all SDKs?

**Comment by andaralex** [comment]
import com.ibm.mobilefirstplatform.clientsdk.android.security.api.AuthenticationContext; 
package used in "bms-clientsdk-cordova-plugin-core/src/android/CDVBMSClient.java" is not supported in Android core sdk 2.+

While using sdk version 2+, need to do lot of changes in all java files under SRC.

I hope, the java files are not updated, sorry if I am mentioned anything wrongly.

**Comment by andaralex** [comment]
one more query, if possible to implement both facebook and google authentication logic based on user preference, in the single application.

**Comment by rotembr** [comment]
Hi, 
You probably configured the gradle to import 'googleauthentication' version 2, this version is currently not supported in the Cordova core SDK, please work with version 1, i.e: 

```
compile group: 'com.ibm.mobilefirstplatform.clientsdk.android',
            name:'googleauthentication',
            version: '1.+',
            ext: 'aar',
            transitive: true 
```

Regarding: 
"...if possible to implement both facebook and google authentication logic based on user preference, in the single application."
Currently multiple identity providers are not supported.

**Comment by dgonz7** [comment]
BMSCore plugin now supports v2 of authentication SDKs, so this issue is fixed. Closing.
