### ISSUE TITLE
Got NullPointerException during BMSAnalytics.initialize

### ISSUE THREAD

**Issue by vgylys** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#26]
I have tried to enable BMSAnalytics on my ionics project, but during the initialization of BMSAnalytics i'm getting NullPointerException when running code on android 6.0.1 device. The code looks like:

`			console.info("Starting uk");
			
			var applicationName = "RaceTrackerMobile";
			var apiKey =  "secret";
			var hasUserContext = false;
			var deviceEvents = [BMSAnalytics.NONE];

			BMSClient.initialize(BMSClient.REGION_UK); //Make sure you point to your region    
			BMSAnalytics.initialize(applicationName, apiKey, hasUserContext, deviceEvents)`

I'm attaching stack trace in the attachment.
[log.txt](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core/files/623086/log.txt)

**Comment by Aerex** [comment]
What version of Cordova are you using? Android 24 is not supported right now.

**Comment by dgonz7** [comment]
Seems this was resolved. Closing this.
