### ISSUE TITLE
Removing the need to modify code

### ISSUE THREAD

**Issue by cfjedimaster** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#5]
Are there plans to remove the need to modify the XCode project? I think it would be desirable for the end user to simply add the plugin. Having to go into the native platform code should - generally - be avoided whenever possible.

**Comment by mjparangot** [comment]
Right now there are no plans. However we have experimented with a Cordova hook script that could remove the need to modify the Xcode project by adding the required lines for you.

**Comment by Aerex** [comment]
@cfjedimaster v2 has included hooks to automatically add in the Bridging Header but there are still some manual steps that needs to be taken. The steps that will need to be taken as of v2 are disabling `Use Legacy Swift` to **NO**
