### ISSUE TITLE
Swift problems

### ISSUE THREAD

**Issue by Saeger** [ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#6]
@objc(CDVBMSClient) class CDVBMSClient : CDVPlugin {

According to 7-10-11 @Apple: 
@objc on Swift-rooted classes never quite behaved like an NSObject-rooted class, leading to various weirdness in the generated header and at runtime. You can still treat any Swift class instance as an AnyObject, mark methods and properties on a Swift class as @objc, and conform to Objective-C protocols; the class just isn't exposed in the generated header and doesn't default to having its members available in Objective-C.

**Comment by dgonz7** [comment]
Cordova does not support Swift, so this issue is invalid until Cordova updates this. Closing this.
